In [2]:
import pandas as pd

In [41]:
df=pd.read_csv(r"/home/aadarsh/Downloads/countries_and_regions (1).csv")
# r"..." → raw string, which treats \ as normal characters.
# On Linux, since paths use /, both are the same.
df

                     Country    Region                 Sub-Region
0                Afghanistan      Asia              Southern Asia
1                    Albania    Europe            Southern Europe
2                    Algeria    Africa            Northern Africa
3                    Andorra    Europe            Southern Europe
4                     Angola    Africa              Middle Africa
5        Antigua and Barbuda  Americas                  Caribbean
6                  Argentina  Americas              South America
7                    Armenia      Asia               Western Asia
8                  Australia   Oceania  Australia and New Zealand
9                    Austria    Europe             Western Europe
10                Azerbaijan      Asia               Western Asia
11                   Bahamas  Americas                  Caribbean
12                   Bahrain      Asia               Western Asia
13                Bangladesh      Asia              Southern Asia
14                  Barbados  Americas                  Caribbean
15                   Belarus    Europe             Eastern Europe
16                   Belgium    Europe             Western Europe
17                    Belize  Americas            Central America
18                     Benin    Africa             Western Africa
19                    Bhutan      Asia              Southern Asia
20                   Bolivia  Americas              South America
21    Bosnia and Herzegovina    Europe            Southern Europe
22                  Botswana    Africa            Southern Africa
23                    Brazil  Americas              South America
24                    Brunei      Asia         South-Eastern Asia
25                  Bulgaria    Europe             Eastern Europe
26              Burkina Faso    Africa             Western Africa
27                   Burundi    Africa             Eastern Africa
28                Cabo Verde    Africa             Western Africa
29                  Cambodia      Asia         South-Eastern Asia
30                  Cameroon    Africa              Middle Africa
31                    Canada  Americas           Northern America
32  Central African Republic    Africa              Middle Africa
33                      Chad    Africa              Middle Africa
34                     Chile  Americas              South America
35                     China      Asia               Eastern Asia
36                  Colombia  Americas              South America
37                   Comoros    Africa             Eastern Africa
38                     Congo    Africa              Middle Africa
39                Costa Rica  Americas            Central America
40                   Croatia    Europe            Southern Europe
41                      Cuba  Americas                  Caribbean
42                    Cyprus      Asia               Western Asia
43            Czech Republic    Europe             Eastern Europe
44                   Denmark    Europe            Northern Europe
45                  Djibouti    Africa             Eastern Africa
46                  Dominica  Americas                  Caribbean
47        Dominican Republic  Americas                  Caribbean
48                   Ecuador  Americas              South America
49                     Egypt    Africa            Northern Africa
50               El Salvador  Americas            Central America
51         Equatorial Guinea    Africa              Middle Africa
52                   Eritrea    Africa             Eastern Africa
53                   Estonia    Europe            Northern Europe
54                  Eswatini    Africa            Southern Africa
55                  Ethiopia    Africa             Eastern Africa
56                      Fiji   Oceania                  Melanesia
57                   Finland    Europe            Northern Europe
58                    France    Europe             Western Europe
59                     Gabon    Africa              Middle Africa
60                    Gambia    Africa             Western Africa
61                   Georgia      Asia               Western Asia
62                   Germany    Europe             Western Europe
63                     Ghana    Africa             Western Africa
64                    Greece    Europe            Southern Europe
65                   Grenada  Americas                  Caribbean
66                 Guatemala  Americas            Central America
67                    Guinea    Africa             Western Africa
68             Guinea-Bissau    Africa             Western Africa
69                    Guyana  Americas              South America
70                     Haiti  Americas                  Caribbean
71                  Honduras  Americas            Central America
72                   Hungary    Europe             Eastern Europe
73                   Iceland    Europe            Northern Europe
74                     India      Asia              Southern Asia
75                 Indonesia      Asia         South-Eastern Asia
76                      Iran      Asia              Southern Asia
77                      Iraq      Asia               Western Asia
78                   Ireland    Europe            Northern Europe
79                    Israel      Asia               Western Asia
80                     Italy    Europe            Southern Europe
81                   Jamaica  Americas                  Caribbean
82                     Japan      Asia               Eastern Asia
83                    Jordan      Asia               Western Asia
84                Kazakhstan      Asia               Central Asia
85                     Kenya    Africa             Eastern Africa
86                  Kiribati   Oceania                 Micronesia
87                    Kuwait      Asia               Western Asia
88                Kyrgyzstan      Asia               Central Asia
89                      Laos      Asia         South-Eastern Asia
90                    Latvia    Europe            Northern Europe
91                   Lebanon      Asia               Western Asia
92                   Lesotho    Africa            Southern Africa
93                   Liberia    Africa             Western Africa
94                     Libya    Africa            Northern Africa
95             Liechtenstein    Europe             Western Europe
96                 Lithuania    Europe            Northern Europe
97                Luxembourg    Europe             Western Europe
98                Madagascar    Africa             Eastern Africa
99                    Malawi    Africa             Eastern Africa

In [43]:
df = pd.read_excel(
    r"/home/aadarsh/Downloads/countries_and_regions.xlsx"
)
df

                     Country    Region                 Sub-Region
0                Afghanistan      Asia              Southern Asia
1                    Albania    Europe            Southern Europe
2                    Algeria    Africa            Northern Africa
3                    Andorra    Europe            Southern Europe
4                     Angola    Africa              Middle Africa
5        Antigua and Barbuda  Americas                  Caribbean
6                  Argentina  Americas              South America
7                    Armenia      Asia               Western Asia
8                  Australia   Oceania  Australia and New Zealand
9                    Austria    Europe             Western Europe
10                Azerbaijan      Asia               Western Asia
11                   Bahamas  Americas                  Caribbean
12                   Bahrain      Asia               Western Asia
13                Bangladesh      Asia              Southern Asia
14                  Barbados  Americas                  Caribbean
15                   Belarus    Europe             Eastern Europe
16                   Belgium    Europe             Western Europe
17                    Belize  Americas            Central America
18                     Benin    Africa             Western Africa
19                    Bhutan      Asia              Southern Asia
20                   Bolivia  Americas              South America
21    Bosnia and Herzegovina    Europe            Southern Europe
22                  Botswana    Africa            Southern Africa
23                    Brazil  Americas              South America
24                    Brunei      Asia         South-Eastern Asia
25                  Bulgaria    Europe             Eastern Europe
26              Burkina Faso    Africa             Western Africa
27                   Burundi    Africa             Eastern Africa
28                Cabo Verde    Africa             Western Africa
29                  Cambodia      Asia         South-Eastern Asia
30                  Cameroon    Africa              Middle Africa
31                    Canada  Americas           Northern America
32  Central African Republic    Africa              Middle Africa
33                      Chad    Africa              Middle Africa
34                     Chile  Americas              South America
35                     China      Asia               Eastern Asia
36                  Colombia  Americas              South America
37                   Comoros    Africa             Eastern Africa
38                     Congo    Africa              Middle Africa
39                Costa Rica  Americas            Central America
40                   Croatia    Europe            Southern Europe
41                      Cuba  Americas                  Caribbean
42                    Cyprus      Asia               Western Asia
43            Czech Republic    Europe             Eastern Europe
44                   Denmark    Europe            Northern Europe
45                  Djibouti    Africa             Eastern Africa
46                  Dominica  Americas                  Caribbean
47        Dominican Republic  Americas                  Caribbean
48                   Ecuador  Americas              South America
49                     Egypt    Africa            Northern Africa
50               El Salvador  Americas            Central America
51         Equatorial Guinea    Africa              Middle Africa
52                   Eritrea    Africa             Eastern Africa
53                   Estonia    Europe            Northern Europe
54                  Eswatini    Africa            Southern Africa
55                  Ethiopia    Africa             Eastern Africa
56                      Fiji   Oceania                  Melanesia
57                   Finland    Europe            Northern Europe
58                    France    Europe             Western Europe
59                     Gabon    Africa              Middle Africa
60                    Gambia    Africa             Western Africa
61                   Georgia      Asia               Western Asia
62                   Germany    Europe             Western Europe
63                     Ghana    Africa             Western Africa
64                    Greece    Europe            Southern Europe
65                   Grenada  Americas                  Caribbean
66                 Guatemala  Americas            Central America
67                    Guinea    Africa             Western Africa
68             Guinea-Bissau    Africa             Western Africa
69                    Guyana  Americas              South America
70                     Haiti  Americas                  Caribbean
71                  Honduras  Americas            Central America
72                   Hungary    Europe             Eastern Europe
73                   Iceland    Europe            Northern Europe
74                     India      Asia              Southern Asia
75                 Indonesia      Asia         South-Eastern Asia
76                      Iran      Asia              Southern Asia
77                      Iraq      Asia               Western Asia
78                   Ireland    Europe            Northern Europe
79                    Israel      Asia               Western Asia
80                     Italy    Europe            Southern Europe
81                   Jamaica  Americas                  Caribbean
82                     Japan      Asia               Eastern Asia
83                    Jordan      Asia               Western Asia
84                Kazakhstan      Asia               Central Asia
85                     Kenya    Africa             Eastern Africa
86                  Kiribati   Oceania                 Micronesia
87                    Kuwait      Asia               Western Asia
88                Kyrgyzstan      Asia               Central Asia
89                      Laos      Asia         South-Eastern Asia
90                    Latvia    Europe            Northern Europe
91                   Lebanon      Asia               Western Asia
92                   Lesotho    Africa            Southern Africa
93                   Liberia    Africa             Western Africa
94                     Libya    Africa            Northern Africa
95             Liechtenstein    Europe             Western Europe
96                 Lithuania    Europe            Northern Europe
97                Luxembourg    Europe             Western Europe
98                Madagascar    Africa             Eastern Africa
99                    Malawi    Africa             Eastern Africa

In [48]:
df2 = pd.read_json(
    r"/home/aadarsh/Downloads/countries_and_regions.json"
)
df2

                     Country    Region                 Sub-Region
0                Afghanistan      Asia              Southern Asia
1                    Albania    Europe            Southern Europe
2                    Algeria    Africa            Northern Africa
3                    Andorra    Europe            Southern Europe
4                     Angola    Africa              Middle Africa
5        Antigua and Barbuda  Americas                  Caribbean
6                  Argentina  Americas              South America
7                    Armenia      Asia               Western Asia
8                  Australia   Oceania  Australia and New Zealand
9                    Austria    Europe             Western Europe
10                Azerbaijan      Asia               Western Asia
11                   Bahamas  Americas                  Caribbean
12                   Bahrain      Asia               Western Asia
13                Bangladesh      Asia              Southern Asia
14                  Barbados  Americas                  Caribbean
15                   Belarus    Europe             Eastern Europe
16                   Belgium    Europe             Western Europe
17                    Belize  Americas            Central America
18                     Benin    Africa             Western Africa
19                    Bhutan      Asia              Southern Asia
20                   Bolivia  Americas              South America
21    Bosnia and Herzegovina    Europe            Southern Europe
22                  Botswana    Africa            Southern Africa
23                    Brazil  Americas              South America
24                    Brunei      Asia         South-Eastern Asia
25                  Bulgaria    Europe             Eastern Europe
26              Burkina Faso    Africa             Western Africa
27                   Burundi    Africa             Eastern Africa
28                Cabo Verde    Africa             Western Africa
29                  Cambodia      Asia         South-Eastern Asia
30                  Cameroon    Africa              Middle Africa
31                    Canada  Americas           Northern America
32  Central African Republic    Africa              Middle Africa
33                      Chad    Africa              Middle Africa
34                     Chile  Americas              South America
35                     China      Asia               Eastern Asia
36                  Colombia  Americas              South America
37                   Comoros    Africa             Eastern Africa
38                     Congo    Africa              Middle Africa
39                Costa Rica  Americas            Central America
40                   Croatia    Europe            Southern Europe
41                      Cuba  Americas                  Caribbean
42                    Cyprus      Asia               Western Asia
43            Czech Republic    Europe             Eastern Europe
44                   Denmark    Europe            Northern Europe
45                  Djibouti    Africa             Eastern Africa
46                  Dominica  Americas                  Caribbean
47        Dominican Republic  Americas                  Caribbean
48                   Ecuador  Americas              South America
49                     Egypt    Africa            Northern Africa
50               El Salvador  Americas            Central America
51         Equatorial Guinea    Africa              Middle Africa
52                   Eritrea    Africa             Eastern Africa
53                   Estonia    Europe            Northern Europe
54                  Eswatini    Africa            Southern Africa
55                  Ethiopia    Africa             Eastern Africa
56                      Fiji   Oceania                  Melanesia
57                   Finland    Europe            Northern Europe
58                    France    Europe             Western Europe
59                     Gabon    Africa              Middle Africa
60                    Gambia    Africa             Western Africa
61                   Georgia      Asia               Western Asia
62                   Germany    Europe             Western Europe
63                     Ghana    Africa             Western Africa
64                    Greece    Europe            Southern Europe
65                   Grenada  Americas                  Caribbean
66                 Guatemala  Americas            Central America
67                    Guinea    Africa             Western Africa
68             Guinea-Bissau    Africa             Western Africa
69                    Guyana  Americas              South America
70                     Haiti  Americas                  Caribbean
71                  Honduras  Americas            Central America
72                   Hungary    Europe             Eastern Europe
73                   Iceland    Europe            Northern Europe
74                     India      Asia              Southern Asia
75                 Indonesia      Asia         South-Eastern Asia
76                      Iran      Asia              Southern Asia
77                      Iraq      Asia               Western Asia
78                   Ireland    Europe            Northern Europe
79                    Israel      Asia               Western Asia
80                     Italy    Europe            Southern Europe
81                   Jamaica  Americas                  Caribbean
82                     Japan      Asia               Eastern Asia
83                    Jordan      Asia               Western Asia
84                Kazakhstan      Asia               Central Asia
85                     Kenya    Africa             Eastern Africa
86                  Kiribati   Oceania                 Micronesia
87                    Kuwait      Asia               Western Asia
88                Kyrgyzstan      Asia               Central Asia
89                      Laos      Asia         South-Eastern Asia
90                    Latvia    Europe            Northern Europe
91                   Lebanon      Asia               Western Asia
92                   Lesotho    Africa            Southern Africa
93                   Liberia    Africa             Western Africa
94                     Libya    Africa            Northern Africa
95             Liechtenstein    Europe             Western Europe
96                 Lithuania    Europe            Northern Europe
97                Luxembourg    Europe             Western Europe
98                Madagascar    Africa             Eastern Africa
99                    Malawi    Africa             Eastern Africa

In [42]:
pd.set_option('display.max.columns',120)
pd.set_option('display.max.rows',100)

In [49]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Country     100 non-null    object
 1   Region      100 non-null    object
 2   Sub-Region  100 non-null    object
dtypes: object(3)
memory usage: 2.5+ KB

In [52]:
df2.shape

(100, 3)

In [53]:
df2.head(11)

                Country    Region                 Sub-Region
0           Afghanistan      Asia              Southern Asia
1               Albania    Europe            Southern Europe
2               Algeria    Africa            Northern Africa
3               Andorra    Europe            Southern Europe
4                Angola    Africa              Middle Africa
5   Antigua and Barbuda  Americas                  Caribbean
6             Argentina  Americas              South America
7               Armenia      Asia               Western Asia
8             Australia   Oceania  Australia and New Zealand
9               Austria    Europe             Western Europe
10           Azerbaijan      Asia               Western Asia

In [57]:
df2.tail(12)

          Country  Region          Sub-Region
88     Kyrgyzstan    Asia        Central Asia
89           Laos    Asia  South-Eastern Asia
90         Latvia  Europe     Northern Europe
91        Lebanon    Asia        Western Asia
92        Lesotho  Africa     Southern Africa
93        Liberia  Africa      Western Africa
94          Libya  Africa     Northern Africa
95  Liechtenstein  Europe      Western Europe
96      Lithuania  Europe     Northern Europe
97     Luxembourg  Europe      Western Europe
98     Madagascar  Africa      Eastern Africa
99         Malawi  Africa      Eastern Africa

In [60]:
df2['Country']

0                  Afghanistan
1                      Albania
2                      Algeria
3                      Andorra
4                       Angola
5          Antigua and Barbuda
6                    Argentina
7                      Armenia
8                    Australia
9                      Austria
10                  Azerbaijan
11                     Bahamas
12                     Bahrain
13                  Bangladesh
14                    Barbados
15                     Belarus
16                     Belgium
17                      Belize
18                       Benin
19                      Bhutan
20                     Bolivia
21      Bosnia and Herzegovina
22                    Botswana
23                      Brazil
24                      Brunei
25                    Bulgaria
26                Burkina Faso
27                     Burundi
28                  Cabo Verde
29                    Cambodia
30                    Cameroon
31                      Canada
32    Central African Republic
33                        Chad
34                       Chile
35                       China
36                    Colombia
37                     Comoros
38                       Congo
39                  Costa Rica
40                     Croatia
41                        Cuba
42                      Cyprus
43              Czech Republic
44                     Denmark
45                    Djibouti
46                    Dominica
47          Dominican Republic
48                     Ecuador
49                       Egypt
50                 El Salvador
51           Equatorial Guinea
52                     Eritrea
53                     Estonia
54                    Eswatini
55                    Ethiopia
56                        Fiji
57                     Finland
58                      France
59                       Gabon
60                      Gambia
61                     Georgia
62                     Germany
63                       Ghana
64                      Greece
65                     Grenada
66                   Guatemala
67                      Guinea
68               Guinea-Bissau
69                      Guyana
70                       Haiti
71                    Honduras
72                     Hungary
73                     Iceland
74                       India
75                   Indonesia
76                        Iran
77                        Iraq
78                     Ireland
79                      Israel
80                       Italy
81                     Jamaica
82                       Japan
83                      Jordan
84                  Kazakhstan
85                       Kenya
86                    Kiribati
87                      Kuwait
88                  Kyrgyzstan
89                        Laos
90                      Latvia
91                     Lebanon
92                     Lesotho
93                     Liberia
94                       Libya
95               Liechtenstein
96                   Lithuania
97                  Luxembourg
98                  Madagascar
99                      Malawi
Name: Country, dtype: object

In [ ]:
df2.loc[89] #Give me the row whose index label is 89.

Country                     Laos
Region                      Asia
Sub-Region    South-Eastern Asia
Name: 89, dtype: object

In [ ]:
df2.loc[89,'Country']

'Laos'

In [ ]:
df2.iloc[89] #Give me the 89th row because Python positions start at 0.

Country                     Laos
Region                      Asia
Sub-Region    South-Eastern Asia
Name: 89, dtype: object

In [73]:
df2.iloc[89,0]

'Laos'